---
- name: restart shibboleth
  become: "{{ ansible_distribution_major_version == '7' }}"
  service: name=shibd state=restarted
  when: ansible_distribution_major_version == '7'

- name: restart shibboleth rhel 6
  command: sudo /sbin/service shibd restart
  when: ansible_distribution_major_version == '6'
