---
- hosts: rate
  tasks:
    - yum:
        pkg: "rh-php56-php-mbstring"
        state: "present"
    - yum:
        pkg: "rh-php56-php-pdo"
        state: "present"
    - yum:
        pkg: "rh-php56-php-xml"
        state: "present"
  vars_prompt:
  - name: "apache_mod_shib_ssl_key_password"
    prompt: "What's the shib key password?"
  roles:
    - apache
    - apache_mod_php
    - apache_mod_shib
    - ipset